<a href="https://colab.research.google.com/github/obidjonqunduzov/data-science/blob/main/03_PANDAS_yakuniy_vazifa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### PANDAS. Yakuniy vazifa. **1-QISM**

In [207]:
import pandas as pd
import numpy as np

In [224]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population.csv", index_col=0)
df

               country     density   densityMi   pop2021     area
rank
1                Macau  21946.4667  56841.3487   658.394       30
2               Monaco  19755.5000  51166.7450    39.511        2
3            Singapore   8305.1915  21510.4461  5896.686      710
4            Hong Kong   6841.3134  17719.0017  7552.810     1104
5            Gibraltar   5616.3333  14546.3033    33.698        6
...                ...         ...         ...       ...      ...
228            Namibia      3.1338      8.1166  2587.344   825615
229     Western Sahara      2.3003      5.9577   611.875   266000
230           Mongolia      2.1286      5.5129  3329.289  1564110
231   Falkland Islands      0.2902      0.7517     3.533    12173
232          Greenland      0.0263      0.0680    56.877  2166086

[232 rows x 5 columns]

### 1-VAZIFA. Yuqoridagi DF ustunlari nomini quyidagi qiymatlarga o'zgartiring va DF yuqorisidan 3 ta davlatni chiqaring
`['davlat','zichlik_km','zichlik_mi','aholi','maydoni']`

In [225]:
# JAVOBNI SHUYERGA YOZING
df.columns=['davlat','zichlik_km','zichlik_mi','aholi','maydoni']
df.head(3)

         davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1         Macau  21946.4667  56841.3487   658.394       30
2        Monaco  19755.5000  51166.7450    39.511        2
3     Singapore   8305.1915  21510.4461  5896.686      710

In [ ]:
#@title To'g'ri javob
df.columns = ['davlat','zichlik_km','zichlik_mi','aholi','maydoni']
df.head(3)

         davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1         Macau  21946.4667  56841.3487   658.394       30
2        Monaco  19755.5000  51166.7450    39.511        2
3     Singapore   8305.1915  21510.4461  5896.686      710

## Yuqoridagi jadval dunyo davlatlarining aholi zichligi bo'yicha reytingini ko'rsatadi.
DF indeksi sifatida davlatning zichlik reytingi olingan (aholi eng zich yashaydigan davlatlar yuqorida).

**Ustunlar:**

`davlat` - Davlat nomi

`zichlik_km` - har 1 kv.km. ga to'g'ri keluvchi aholi soni

`zichlik_mi` - har 1 kv.milyaga to'g'ri keluvchi aholi soni (milya - AQSh masofa o'lchov birligi)

`aholi` - 2021-yilga ko'rsa aholi soni (ming)

`maydoni` - davlat maydoni (kv.km)

### 2-VAZIFA. DF oxiridan 10 ta qator chiqaring.

In [226]:
# JAVOBNI SHUYERGA YOZING
df.tail(10)

                davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
223             Guyana      3.6765      9.5220    790.326   214969
224      French Guiana      3.6685      9.5015    306.448    83534
225           Suriname      3.6125      9.3564    591.800   163820
226          Australia      3.3526      8.6832  25788.215  7692024
227            Iceland      3.3335      8.6338    343.353   103000
228            Namibia      3.1338      8.1166   2587.344   825615
229     Western Sahara      2.3003      5.9577    611.875   266000
230           Mongolia      2.1286      5.5129   3329.289  1564110
231   Falkland Islands      0.2902      0.7517      3.533    12173
232          Greenland      0.0263      0.0680     56.877  2166086

### 3-VAZIFA. DF dan 10, 20, 100, 200-indekslarda turgan davlatlarni alohida DF ko'rinishida chiqaring.

In [227]:
# JAVOBNI SHUYERGA YOZING
df.loc[[10,20,100,200]]

           davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
10        Bermuda   1149.8148   2978.0204    62.090       54
20          Aruba    595.5778   1542.5464   107.204      180
100      Slovakia    111.3592    288.4203  5460.721    49037
200   New Zealand     17.9713     46.5457  4860.643   270467

### 4-VAZIFA. Davlatlar orasida `Uzbekistan`, `Hong-Kong`, `Antartica` borligini tekshiring

In [229]:
# JAVOBNI SHUYERGA YOZING
df_new = df
pd.Index(['Uzbekistan','Hong-Kong','Antartica' ]).isin(df_new.index)

array([ True, False, False])

### 5-VAZIFA.
#### 5.1 DFning `davlat` nomli ustunini uning indeksi qilib belgilang.
#### 5.2 `davlat` ustunini tashlab yuboring.
#### 5.3 DFni davlat nomi bo'yicha tartiblang

In [228]:
# JAVOBNI SHUYERGA YOZING
df.set_index(df.columns[0], inplace=True)
df.head()

           zichlik_km  zichlik_mi     aholi  maydoni
davlat
Macau      21946.4667  56841.3487   658.394       30
Monaco     19755.5000  51166.7450    39.511        2
Singapore   8305.1915  21510.4461  5896.686      710
Hong Kong   6841.3134  17719.0017  7552.810     1104
Gibraltar   5616.3333  14546.3033    33.698        6

In [ ]:
#@title Kutilayotgan natija

                zichlik_km  zichlik_mi      aholi  maydoni
davlat
Afghanistan        61.0757    158.1862  39835.428   652230
Albania            99.9351    258.8318   2872.933    28748
Algeria            18.7328     48.5179  44616.624  2381741
American Samoa    276.8844    717.1307     55.100      199
Andorra           165.2885    428.0971     77.355      468

### 6-VAZIFA. DF dan `Uzbekistan`, `Malaysia`, `South Korea`, `France` davlatlari `aholi` va `maydoni` ustunlari bilan alohida DF ko'rinishida ajratib oling.

In [63]:
# JAVOBNI SHUYERGA YOZING
df.loc[['Uzbekistan','Malaysia','South Korea','France'],['aholi','maydoni']]

                 aholi  maydoni
davlat
Uzbekistan   33935.763   447400
Malaysia     32776.194   330803
South Korea  51305.186   100210
France       65426.179   551695

In [ ]:
#@title O'xshash natija (boshqa davlatlar uchun)

                 aholi  maydoni
davlat
Singapore     5896.686      710
North Korea  25887.041   120538
Germany      83900.473   357114
Kazakhstan   18994.962  2724900

### 7-VAZIFA. Asl DFning `aholi` ustuni qiymatlarini 1000 ga ko'paytiring.

In [74]:
# JAVOBNI SHUYERGA YOZING
df*1000
df.sort_index()

                   zichlik_km  zichlik_mi      aholi  maydoni
davlat
Afghanistan           61.0757    158.1862  39835.428   652230
Albania               99.9351    258.8318   2872.933    28748
Algeria               18.7328     48.5179  44616.624  2381741
American Samoa       276.8844    717.1307     55.100      199
Andorra              165.2885    428.0971     77.355      468
...                       ...         ...        ...      ...
Wallis and Futuna     78.1268    202.3483     11.094      142
Western Sahara         2.3003      5.9577    611.875   266000
Yemen                 57.7509    149.5749  30490.640   527968
Zambia                25.1400     65.1125  18920.651   752612
Zimbabwe              38.6229    100.0333  15092.171   390757

[232 rows x 4 columns]

In [ ]:
#@title Kutilgan natija

                zichlik_km  zichlik_mi       aholi  maydoni
davlat
Afghanistan        61.0757    158.1862  39835428.0   652230
Albania            99.9351    258.8318   2872933.0    28748
Algeria            18.7328     48.5179  44616624.0  2381741
American Samoa    276.8844    717.1307     55100.0      199
Andorra           165.2885    428.0971     77355.0      468

DF ni `aholi` ustuni bo'yicha kamayish tartibida tahlang va aholisi eng kam 10 ta davlatni chiqaring.

In [116]:
# JAVOBNI SHUYERGA YOZING
df['aholi'].rank(method='min')
df.sort_values('aholi')

                  zichlik_km  zichlik_mi        aholi  maydoni
davlat
Vatican City        800.0000   2072.0000        0.800        1
Tokelau             114.4167    296.3392        1.373       12
Niue                  6.2269     16.1277        1.619      260
Falkland Islands      0.2902      0.7517        3.533    12173
Montserrat           48.7941    126.3768        4.977      102
...                      ...         ...          ...      ...
Pakistan            255.3542    661.3674   225199.937   881912
Indonesia           145.1046    375.8210   276361.783  1904569
United States        35.5200     91.9968   332915.073  9372610
India               423.8391   1097.7432  1393409.038  3287590
China               148.7815    385.3441  1444216.107  9706961

[232 rows x 4 columns]

### 8-VAZIFA. DFni `maydoni` bo'yicha reytinglang (rank) va reytinglarni yangi `rank` ustuniga yozing.

In [119]:
# JAVOBNI SHUYERGA YOZING
df['rank'] = df['maydoni'].rank()
df.sort_index()

                   zichlik_km  zichlik_mi      aholi  maydoni   rank
davlat
Afghanistan           61.0757    158.1862  39835.428   652230  192.0
Albania               99.9351    258.8318   2872.933    28748   89.0
Algeria               18.7328     48.5179  44616.624  2381741  223.0
American Samoa       276.8844    717.1307     55.100      199   20.0
Andorra              165.2885    428.0971     77.355      468   38.0
...                       ...         ...        ...      ...    ...
Wallis and Futuna     78.1268    202.3483     11.094      142   15.0
Western Sahara         2.3003      5.9577    611.875   266000  155.0
Yemen                 57.7509    149.5749  30490.640   527968  183.0
Zambia                25.1400     65.1125  18920.651   752612  194.0
Zimbabwe              38.6229    100.0333  15092.171   390757  172.0

[232 rows x 5 columns]

In [ ]:
#@title Kutilgan natija

                   zichlik_km  zichlik_mi       aholi  maydoni   rank
davlat
Afghanistan           61.0757    158.1862  39835428.0   652230  192.0
Albania               99.9351    258.8318   2872933.0    28748   89.0
Algeria               18.7328     48.5179  44616624.0  2381741  223.0
American Samoa       276.8844    717.1307     55100.0      199   20.0
Andorra              165.2885    428.0971     77355.0      468   38.0
...                       ...         ...         ...      ...    ...
Wallis and Futuna     78.1268    202.3483     11094.0      142   15.0
Western Sahara         2.3003      5.9577    611875.0   266000  155.0
Yemen                 57.7509    149.5749  30490640.0   527968  183.0
Zambia                25.1400     65.1125  18920651.0   752612  194.0
Zimbabwe              38.6229    100.0333  15092171.0   390757  172.0

[232 rows x 5 columns]

#### `Uzbekistan`, `United Kingdom`, `Indonesia` davlatlari alohida df ko'rinishida chiqaring

In [121]:
# JAVOBNI SHUYERGA YOZING
df.loc[['Uzbekistan','United Kingdom','Indonesia']]

                zichlik_km  zichlik_mi       aholi  maydoni   rank
davlat
Uzbekistan         75.8511    196.4542   33935.763   447400  176.0
United Kingdom    280.8033    727.2805   68207.116   242900  153.0
Indonesia         145.1046    375.8210  276361.783  1904569  218.0

In [ ]:
#@title O'xshash natija (boshqa davlatlar uchun)

               zichlik_km  zichlik_mi        aholi  maydoni   rank
davlat
Turkmenistan      12.5342     32.4635    6117924.0   488100  180.0
United States     35.5200     91.9968  332915073.0  9372610  229.0
Vietnam          296.3927    767.6572   98168833.0   331212  166.0

### 9-VAZIFA. DFni `davlat` nomi bo'yicha tartiblang.

In [125]:
# JAVOBNI SHUYERGA YOZING
df.sort_index()

                   zichlik_km  zichlik_mi      aholi  maydoni   rank
davlat
Afghanistan           61.0757    158.1862  39835.428   652230  192.0
Albania               99.9351    258.8318   2872.933    28748   89.0
Algeria               18.7328     48.5179  44616.624  2381741  223.0
American Samoa       276.8844    717.1307     55.100      199   20.0
Andorra              165.2885    428.0971     77.355      468   38.0
...                       ...         ...        ...      ...    ...
Wallis and Futuna     78.1268    202.3483     11.094      142   15.0
Western Sahara         2.3003      5.9577    611.875   266000  155.0
Yemen                 57.7509    149.5749  30490.640   527968  183.0
Zambia                25.1400     65.1125  18920.651   752612  194.0
Zimbabwe              38.6229    100.0333  15092.171   390757  172.0

[232 rows x 5 columns]

In [ ]:
#@title Kutilgan natija

                zichlik_km  zichlik_mi       aholi  maydoni   rank
davlat
Afghanistan        61.0757    158.1862  39835428.0   652230  192.0
Albania            99.9351    258.8318   2872933.0    28748   89.0
Algeria            18.7328     48.5179  44616624.0  2381741  223.0
American Samoa    276.8844    717.1307     55100.0      199   20.0
Andorra           165.2885    428.0971     77355.0      468   38.0

#### DFdan 10,50,100,200-o'rinda turgan davlatlarni alohida DF ko'rinishida chiqaring

In [140]:
# JAVOBNI SHUYERGA YOZING
df.iloc[[10,50,100,200]]

                     zichlik_km  zichlik_mi       aholi  maydoni   rank
davlat
Bangladesh            1126.9465   2918.7915  166303.498   147570  139.0
Trinidad and Tobago    273.5624    708.5266    1403.375     5130   61.0
Benin                  110.5560    286.3401   12451.040   112622  131.0
Paraguay                17.7495     45.9712    7219.638   406752  173.0

In [ ]:
#@title O'xshash natija (boshqa qatorlar uchun)

                              zichlik_km  zichlik_mi     aholi  maydoni  rank
davlat
Belize                           17.6310     45.6643  404914.0    22966  82.0
French Polynesia                 67.8018    175.6066  282530.0     4167  60.0
Guadeloupe                      245.7125    636.3955  400020.0     1628  53.0
United States Virgin Islands    300.3631    777.9405  104226.0      347  29.0

### 10-VAZIFA. Quyidagi davlatlarning `aholi` sonini oddiy son ko'rinishida chiqaring:
- `Malaysia`
- `Nigeria`
- `Nepal`
- `Italy`

In [161]:
# JAVOBNI SHUYERGA YOZING
df.at['Malaysia','aholi']

32776.194

In [162]:
df.at['Nigeria','aholi']

211400.708

In [164]:
df.at['Nepal','aholi']

29674.92

In [165]:
df.at['Italy','aholi']

60367.477

In [ ]:
#@title o'xshash natija (`Uzbekistan` uchun)

33935763.0